# Generated by Django 3.2.8 on 2021-11-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dclass_application', '0002_classes_class_name'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_class',
            field=models.ManyToManyField(blank=True, to='dclass_application.Classes'),
        ),
    ]
