# Generated by Django 3.2.8 on 2021-10-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dclass_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_name',
            field=models.CharField(default='English', max_length=100),
            preserve_default=False,
        ),
    ]
