# Generated by Django 3.2.8 on 2021-11-08 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dclass_application', '0006_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
