# Generated by Django 3.2.8 on 2021-11-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dclass_application', '0007_delete_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
    ]
