# Generated by Django 3.2.8 on 2021-11-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dclass_application', '0009_auto_20211118_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='three_ago_a_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='classes',
            name='two_ago_a_ratio',
            field=models.FloatField(default=0.0),
        ),
    ]
