# Generated by Django 3.2.8 on 2021-11-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dclass_application', '0010_auto_20211118_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='credict',
            new_name='credit',
        ),
    ]
